services:
  # backend:
  #   build: ./backend
  #   command: mix phx.server
  #   environment:
  #     DATABASE_URL: ecto://postgres:postgres@db:5432/app_db
  #     # OR whatever your Repo expects:
  #     # POSTGRES_USER: postgres
  #     # POSTGRES_PASSWORD: postgres
  #     # POSTGRES_DB: app_db
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - db

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orca_backend_dev 
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # Needed if you want to access with Postico/PgAdmin locally

volumes:
  db_data:
